### ISSUE TITLE
The Google drive link for kernel ain't working

### ISSUE THREAD

**Issue by rohit30san** [FawkesOficial/Nethunter-Build---Redmi-Note-4-mido-#1]
The link for the kernel on xda thread ain't working I searched all over internet still can't find other link

**Comment by FawkesOficial** [comment]
Hey, sorry for taking so long to respond. I was on vacation :)

I've updated the download link for the kernel in the README. Here's the link:

https://drive.google.com/file/d/10iV4EOiKHgeckhJAMj__xD3R2sn6t3DI/view?usp=sharing

If you need any other file, just ask.
